# Generated by Django 4.1.2 on 2022-11-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneyapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="People",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name1", models.CharField(max_length=250)),
                ("img1", models.ImageField(upload_to=250)),
                ("desc1", models.TextField()),
            ],
        ),
    ]
